[general]
name = "NanoVM"
description = "MicroVM environment with customized nano text editor"
target_arch = "aarch64"

[kernel]
version = "6.9.4"
url = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.9.4.tar.xz"
[kernel.options]
BINFMT_ELF = "y"
BINFMT_SCRIPT = "y"
EXPERT = "y"
SWAP = "n"
FRAMEBUFFER_CONSOLE = "y"
FONTS = "y"
FONT_8x8 = "y"
FONT_8x16 = "y"
UNIX = "y"
TMPFS = "y"
DEVTMPFS = "y"
DEVTMPFS_MOUNT = "y"
PROC_FS = "y"
SYSFS = "y"
BLOCK = "y"
PRINTK = "y"
VT = "y"
VT_CONSOLE = "y"
HW_CONSOLE = "y"
INPUT_KEYBOARD = "y"
INPUT_MOUSE = "n"
INPUT_EVDEV = "y"
TTY = "y"
HID_SUPPORT = "n"
UNIX98_PTYS = "y"
SERIO = "y"
EXT4_FS = "y"
SQUASHFS = "y"
FB = "y"
FB_SIMPLE = "y"
FB_CORE = "y"
VGA_CONSOLE = "y"
SYSFB = "y"
SYSFB_SIMPLEFB = "y"
DEBUG_INFO_NONE = "y"
PREEMPT_NONE_BUILD = "y"
TINY_RCU = "y"
BLK_DEV_INITRD = "y"
CC_OPTIMIZE_FOR_SIZE = "y"
SERIAL_AMBA_PL011 = "y"
SERIAL_AMBA_PL011_CONSOLE = "y"
SERIAL_CORE = "y"
SERIAL_CORE_CONSOLE = "y"
SERIAL_DEV_BUS = "y"
SERIAL_DEV_CTRL_TTYPORT = "y"



[applications.nano]
name = "Nano"
version = "8.0"
url = "https://www.nano-editor.org/dist/v8/nano-8.0.tar.gz"
config_script = "./configure CFLAGS=-static LDFLAGS=-static"
output_executable_path = "/usr/local/bin/nano"

[boot]
cmdline = "console=ttyAMA0"
initramfs = true

[output]
format = "qemu_image"
image_name = "NanoVM.img"