[general]
name = "LynxVM"
description = "Lightweight VM running the Lynx text-based web browser"
target_arch = "aarch64"

[kernel]
version = "6.9.4"
url = "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.9.4.tar.xz"
[kernel.options]
CC_OPTIMIZE_FOR_SIZE = "y"
DEBUG_INFO_NONE = "y"
BLK_DEV_INITRD = "y"
EXPERT = "y"
TINY_RCU = "y"
PREEMPT_NONE_BUILD = "y"
PRINTK = "y"
HZ_1000 = "y"
BLOCK = "y"
MQ_IOSCHED_DEADLINE = "n"
MQ_IOSCHED_KYBER = "n"
DEVTMPFS = "y"
DEVTMPFS_MOUNT = "y"
PROC_FS = "y"
SYSFS = "y"
PROC_PAGE_MONITOR = "n"
NETWORK_FILESYSTEMS = "n"
FUTEX = "y"
SWAP = "n"
TTY = "y"
UNIX98_PTYS = "y"
SERIO = "y"
SERIAL_CORE = "y"
SERIAL_CORE_CONSOLE = "y"
SERIAL_AMBA_PL011 = "y"
SERIAL_AMBA_PL011_CONSOLE = "y"
SERIAL_DEV_BUS = "y"
SERIAL_DEV_CTRL_TTYPORT = "y"
NET = "y"
NET_CORE = "y"
ETHERNET = "n"
NETDEVICES = "y"
INET = "y"
TCP = "y"
UNIX = "y"
PACKET = "y"
NETLINK_DIAG = "y"
WLAN = "n"
WIRELESS = "n"
ETHTOOL_NETLINK = "n"
PCI = "y"
PCI_MSI = "y"
VIRTIO_MENU = "y"
VIRTIO = "y"
VIRTIO_PCI = "y"
VIRTIO_NET = "y"
VIRTIO_MMIO = "y"
BINFMT_ELF = "y"
BINFMT_SCRIPT = "y"
INPUT_KEYBOARD = "n"
INPUT_MOUSE = "n"
INPUT_EVDEV = "n"
HID_SUPPORT = "n"
VT = "y"
VT_CONSOLE = "y"
HW_CONSOLE = "n"
EXT4_FS = "n"
SQUASHFS = "n"
FB = "n"
FB_SIMPLE = "n"
FB_CORE = "n"
VGA_CONSOLE = "n"
SYSFB = "n"
SYSFB_SIMPLEFB = "n"

[applications.lynx]
name = "lynx"
version = "2.9.2"
url = "https://invisible-island.net/archives/lynx/tarballs/lynx2.9.2.tar.gz"
config_script = "./configure --enable-static-bin --with-ssl=/usr  --with-ssl-includes=/usr/include/openssl --with-ssl-libraries=/usr/lib CFLAGS=-static LDFLAGS='-L/usr/lib -static'"
output_executable_path = "/usr/local/bin/lynx 207.241.224.2"
include_net = true

[boot]
cmdline = "console=ttyAMA0"
initramfs = true

[boot.network]
enable = true  # Boolean to enable/disable network support
interface = "net0"  # Defined interface name


[output]
format = "qemu_image"
image_name = "LynxVM.img"
