[general]
name = "MariaDBMicroVM"
description = "Lightweight MicroVM environment with MariaDB database server"
target_arch = "aarch64"

[kernel]
version = "6.9.7"

[kernel.options]
CC_OPTIMIZE_FOR_SIZE = "y"
DEBUG_INFO_NONE = "y"
BLK_DEV_INITRD = "y"
EXPERT = "y"
TINY_RCU = "y"
PRINTK = "y"
PREEMPT_NONE_BUILD = "y"
HZ_1000 = "y"
BLOCK = "y"
MQ_IOSCHED_DEADLINE = "n"
MQ_IOSCHED_KYBER = "n"
DEVTMPFS = "y"
DEVTMPFS_MOUNT = "y"
PROC_FS = "y"
SYSFS = "y"
PROC_PAGE_MONITOR = "n"
NETWORK_FILESYSTEMS = "n"
FUTEX = "y"
SWAP = "n"
TTY = "y"
UNIX98_PTYS = "y"
SERIO = "y"
SERIAL_CORE = "y"
SERIAL_CORE_CONSOLE = "y"
SERIAL_AMBA_PL011 = "y"
SERIAL_AMBA_PL011_CONSOLE = "y"
SERIAL_DEV_BUS = "y"
SERIAL_DEV_CTRL_TTYPORT = "y"
NET = "y"
NET_CORE = "y"
ETHERNET = "n"
NETDEVICES = "y"
INET = "y"
TCP = "y"
UNIX = "y"
PACKET = "y"
NETLINK_DIAG = "y"
WLAN = "n"
WIRELESS = "n"
ETHTOOL_NETLINK = "n"
PCI = "y"
PCI_MSI = "y"
VIRTIO_MENU = "y"
VIRTIO = "y"
VIRTIO_PCI = "y"
VIRTIO_NET = "y"
VIRTIO_MMIO = "y"
BINFMT_ELF = "y"
BINFMT_SCRIPT = "y"
INPUT_KEYBOARD = "n"
INPUT_MOUSE = "n"
INPUT_EVDEV = "n"
HID_SUPPORT = "n"
VT = "y"
VT_CONSOLE = "y"
HW_CONSOLE = "n"
EXT4_FS = "n"
SQUASHFS = "n"
FB = "n"
FB_SIMPLE = "n"
FB_CORE = "n"
VGA_CONSOLE = "n"
SYSFB = "n"
SYSFB_SIMPLEFB = "n"

[applications.mariadb]
name = "MariaDB"
version = "11.6"
url = "https://archive.mariadb.org/mariadb-11.6/source/mariadb-11.6.0.tar.gz"
config_script = "cmake . -DWITH_STATIC=ON -DWITH_INNOBASE_STORAGE_ENGINE=1 -DWITH_PARTITION_STORAGE_ENGINE=1 -DPLUGIN_AUTH_PAM=NO -DWITHOUT_TOKUDB=1 -DWITHOUT_ROCKSDB=1 -DPLUGIN_TOKUDB=NO -DPLUGIN_ROCKSDB=NO -DWITH_SSL=bundled -DWITH_ZLIB=bundled -DWITH_PCRE=bundled -DWITH_EDITLINE=bundled -DBUILD_CONFIG=mysql_release -DPLUGIN_PARTITION=STATIC -DWITH_EMBEDDED_SERVER=ON -DWITH_SYSTEMD=no -DSKIP_TESTS=ON -DCMAKE_EXE_LINKER_FLAGS='-static -static-libgcc -static-libstdc++ -lnettle -lgmp' -DCMAKE_FIND_LIBRARY_SUFFIXES='.a' -DWITH_DYNAMIC_PLUGINS=OFF"
build_command = "make"
install_command = "make install"
output_executable_path = "/usr/local/mysql/bin/mariadbd --datadir=/var/lib/mysql --socket=/var/run/mysqld/mysqld.sock --port=3306 --bind-address=127.0.0.1 --log-error=/var/log/mysql/error.log --pid-file=/var/run/mysqld/mysqld.pid"
include_net = true

[boot]
cmdline = "console=ttyAMA0"

[boot.network]
enable = true
interface = "net0"
ip_address = "192.168.1.9"
netmask = "255.255.255.0"
gateway = "192.168.1.64"

[output]
format = "qemu_image"
image_name = "MariaDBMicroVM.img"
