[general]
name = "MicroHTTPdVM"
description = "Lightweight VM running Micro HTTPd for serving static pages"
target_arch = "x86_64"

[kernel]
version = "5.4"
options = { CONFIG_INET = "y", CONFIG_SERIAL = "y", CONFIG_BLOCK = "n" }
patches = ["patches/disable_unused_drivers.patch"]

[applications.microhttpd]
version = "latest"
url = "http://www.acme.com/software/micro_httpd/micro_httpd_14Aug2014.tar.gz"
config_script = "scripts/configure_microhttpd.sh"

[boot]
cmdline = "console=ttyS0 root=/dev/ram0"
initramfs = true

[output]
format = "qemu_image"
image_name = "MicroHTTPdVM.img"
