[general]
name = "NanoEditorVM"
description = "Lightweight VM running Nano editor"
target = "x86_64"

[kernel]
version = "5.4"
#config = "configs/kernel_x86_64_minimal.config"
options = { CONFIG_INET = "y", CONFIG_SERIAL = "y", CONFIG_BLOCK = "n" }
patches = ["patches/disable_unused_drivers.patch"]


[applications.nano]
version = "latest"
url = "https://www.nano-editor.org/download.php"
config_script = "scripts/configure_nano.sh"

[boot]
cmdline = "console=ttyS0"
initramfs = true

[output]
format = "qemu_image"
image_name = "NanoEditorVM.img"