[general]
name = "PostgreSQLMicroVM"
description = "Lightweight MicroVM environment with PostgreSQL database server"
target_arch = "aarch64"

[kernel]
version = "6.9.7"

[kernel.options]
CC_OPTIMIZE_FOR_SIZE = "y"
DEBUG_INFO_NONE = "y"
BLK_DEV_INITRD = "y"
EXPERT = "y"
TINY_RCU = "y"
PRINTK = "y"
PREEMPT_NONE_BUILD = "y"
HZ_1000 = "y"
BLOCK = "y"
MQ_IOSCHED_DEADLINE = "n"
MQ_IOSCHED_KYBER = "n"
DEVTMPFS = "y"
DEVTMPFS_MOUNT = "y"
PROC_FS = "y"
SYSFS = "y"
PROC_PAGE_MONITOR = "n"
NETWORK_FILESYSTEMS = "n"
FUTEX = "y"
SWAP = "n"
TTY = "y"
UNIX98_PTYS = "y"
SERIO = "y"
SERIAL_CORE = "y"
SERIAL_CORE_CONSOLE = "y"
SERIAL_AMBA_PL011 = "y"
SERIAL_AMBA_PL011_CONSOLE = "y"
SERIAL_DEV_BUS = "y"
SERIAL_DEV_CTRL_TTYPORT = "y"
NET = "y"
NET_CORE = "y"
ETHERNET = "n"
NETDEVICES = "y"
INET = "y"
TCP = "y"
UNIX = "y"
PACKET = "y"
NETLINK_DIAG = "y"
WLAN = "n"
WIRELESS = "n"
ETHTOOL_NETLINK = "n"
PCI = "y"
PCI_MSI = "y"
VIRTIO_MENU = "y"
VIRTIO = "y"
VIRTIO_PCI = "y"
VIRTIO_NET = "y"
VIRTIO_MMIO = "y"
BINFMT_ELF = "y"
BINFMT_SCRIPT = "y"
INPUT_KEYBOARD = "n"
INPUT_MOUSE = "n"
INPUT_EVDEV = "n"
HID_SUPPORT = "n"
VT = "y"
VT_CONSOLE = "y"
HW_CONSOLE = "n"
EXT4_FS = "n"
SQUASHFS = "n"
FB = "n"
FB_SIMPLE = "n"
FB_CORE = "n"
VGA_CONSOLE = "n"
SYSFB = "n"
SYSFB_SIMPLEFB = "n"

[applications.postgresql]
name = "PostgreSQL"
version = "16.3"
url = "https://ftp.postgresql.org/pub/source/v16.3/postgresql-16.3.tar.gz"
config_script = "./configure -q --without-readline --without-zlib --without-icu --without-python --without-selinux"
build_command = "make"
install_command = "make install"
output_executable_path = "/usr/local/pgsql/bin/postgres"
include_net = true

[boot]
cmdline = "console=ttyAMA0"

[boot.network]
enable = true
interface = "net0"
ip_address = "192.168.1.9"
netmask = "255.255.255.0"
gateway = "192.168.1.64"

[output]
format = "qemu_image"
image_name = "PostgreSQLMicroVM.img"
